pipeline {
    agent any

    environment {
        IMAGE_NAME = 'arman/docker-springboot'
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Ak-Arman/springboot-arman.git'
            }
        }

        stage('Build & Test') {
            steps {
                sh 'mvn clean test'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh 'mvn sonar:sonar'
                }
            }
        }

        stage('Docker Build') {
            steps {
                sh 'mvn clean package'
                sh 'docker build -t $IMAGE_NAME .'
            }
        }

        stage('Scan with Trivy') {
            steps {
                sh 'trivy image $IMAGE_NAME || true'
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                        docker push $IMAGE_NAME
                    '''
                }
            }
        }

        stage('Deploy') {
            steps {
                sh 'docker run -d -p 8080:8080 $IMAGE_NAME'
            }
        }
    }
}
